name: Create and Upload Release Zip

on:
  push:
    tags:
      - 'dist/v**'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Remove .gitignore and Gemfile
        run: |
          rm -f .gitignore Gemfile

      - name: Remove unit test folder and reference
        run: |
          rm -rf obusdk-ios-sampleTests
          sed -i '' '/obusdk-ios-sampleTests/d' obusdk-ios-sample.xcodeproj/project.pbxproj

      - name: Create a zip of the project
        run: |
          zip -r project.zip .

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}  # Tag that triggered the workflow
          release_name: obusdk-ios-dist-${{ steps.split.outputs._1 }}
          draft: false
          prerelease: false
          body: |
            Release notes for version ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token for authentication

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}  # URL to upload the asset
          asset_path: ./project.zip
          asset_name: project.zip
          asset_content_type: application/zip
