name: iOS Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macOS-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Install CocoaPods
      run: |
        gem install cocoapods
        pod install
    
    - name: Build and Run on Simulator
      run: |
        # xcodebuild \
        #   -workspace obusdk-ios-sample.xcworkspace \
        #   -scheme obusdk-ios-sample \
        #   -destination 'platform=iOS Simulator, name:Any iOS Simulator Device' \
        #   clean build test
          xcodebuild test -scheme obusdk-ios-sample -destination "name=iPhone 15 Pro" | xcpretty && exit ${PIPESTATUS[0]}

         # { platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
